version: '3.8'
services:
  data_agent:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TENANT_ID=${TENANT}
      - DATA_AGENT_URL=${DATA_AGENT}
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./data_viz:/app/data_viz